# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # vagrant plugin install vagrant-hostmanager
   config.hostmanager.enabled = true
   config.hostmanager.ignore_private_ip = false
   config.hostmanager.include_offline = true

   config.vm.define "node1" do |node1|
   node1.vm.box = "bento/centos-6.7"
   node1.vm.hostname = "node1.mylab.local"
   node1.vm.network :private_network, ip: "192.168.56.11"
   end

   config.vm.define "node2" do |node2|
   node2.vm.box = "bento/centos-6.7"
   node2.vm.hostname = "node2.mylab.local"
   node2.vm.network :private_network, ip: "192.168.56.12"
   end
	
   config.vm.define "node3" do |node3|
   node3.vm.box = "centos/7"
   node3.vm.hostname = "node3.mylab.local"
   node3.vm.network :private_network, ip: "192.168.56.13"
   end
   
   config.vm.define "node4" do |node4|
   node4.vm.box = "ubuntu/trusty64"
   node4.vm.hostname = "node4.mylab.local"
   node4.vm.network :private_network, ip: "192.168.56.14"
   end
end